name: main
on:
  push: { paths: ["*.nix",".github/workflows/main.yml"] }
  pull_request: { paths: ["*.nix",".github/workflows/main.yml"] }
  workflow_call:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the project.
        uses: actions/checkout@v2

      - name: setup nix.
        uses: polis-dev/acts/setup-nix@main
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: print flake info.
        run: nix flake show && echo && nix flake metadata && echo
