name: main
on:
  push: { branches: ["main"], paths: ["*.nix", ".github/workflows/main.yml"] }
  pull_request: { branches: ["main"], paths: ["*.nix", ".github/workflows/main.yml"] }
  workflow_call:
  workflow_dispatch:
  schedule: [{ cron: "0 7,14 * * *" }]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the project.
        uses: actions/checkout@v2
      - name: setup nix.
        uses: polis-dev/acts/setup-nix@main
        with:
          nix_path: >-
            nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |-
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            warn-dirty = false
            print-missing = false
            preallocate-contents = true
            max-jobs = auto
            allow-dirty = true
            experimental-features = flakes nix-command
            show-trace = true
            enforce-determinism = true
      - name: initialize flake.
        run: nix flake prefetch --quiet
      - name: flake inputs.
        run: nix flake metadata --offline --quiet
      - name: flake outputs.
        run: nix flake show --offline --quiet
      - name: build default package.
        run: nix build --offline
      - name: output fly version.
        run: ./result/bin/fly --version
      - name: output concourse version.
        run: ./result/bin/fly --version
      - name: upload result.
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result/*
          if-no-files-found: error
          retention-days: 2
