name: main
on:
  push: { branches: ["main"], paths: ["*.nix", ".github/workflows/main.yml"] }
  pull_request: { branches: ["main"], paths: ["*.nix", ".github/workflows/main.yml"] }
  workflow_call:
  workflow_dispatch:
  schedule: [{ cron: "0 7,14 * * *" }]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:

      - name: checkout the project.
        uses: actions/checkout@v3

      - name: setup nix.
        uses: polis-dev/acts/setup-nix@main
        with:
          packages: cachix
          extra_nix_config: |-
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: initialize flake.
        run: nix flake prefetch --quiet

      - name: flake inputs.
        run: nix flake metadata --offline --quiet

      - name: flake outputs.
        run: nix flake show --offline --quiet

      - name: build default package.
        run: nix build && echo "$PWD/result/bin" >>$GITHUB_PATH

      - name: output fly version & --help.
        run: fly --version && echo && fly --help

      - name: output concourse version & --help.
        run: concourse --version && echo && concourse --help

      - name: upload result.
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result/bin/*
          if-no-files-found: warn
          retention-days: 2
