name: main
on:
  push: { branches: ["main"], paths: ["*.nix",".github/workflows/main.yml"] }
  pull_request: { branches: ["main"], paths: ["*.nix",".github/workflows/main.yml"] }
  workflow_call:
  workflow_dispatch:
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the project.
        uses: actions/checkout@v2
      - name: setup nix.
        uses: polis-dev/acts/setup-nix@main
        with:
          nix_path: >-
            nixpkgs=channel:nixos-unstable
          extra_nix_config: |-
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            warn-dirty = false
            print-missing = false
            preallocate-contents = true
            max-jobs = auto
            allow-dirty = true
            experimental-features = flakes nix-command ca-derivations
            show-trace = true
            enforce-determinism = true
      - name: initialize flake.
        run: nix flake prefetch --quiet
      - name: flake inputs.
        run: nix flake metadata --offline --quiet
      - name: flake outputs.
        run: nix flake show --offline --quiet
      - name: ensure default package/app builds & runs.
        continue-on-error: true
        run: "nix run .#fly -- --version"
