name: main
on:
  push: { paths: ["*.nix",".github/workflows/main.yml"] }
  pull_request: { paths: ["*.nix",".github/workflows/main.yml"] }
  workflow_call:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the project.
        uses: actions/checkout@v2
      - name: setup nix.
        uses: polis-dev/acts/setup-nix@main
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: pre-fetch flake & dependencies.
        run: nix flake prefetch --no-write-lock-file
      - name: nix flake inputs.
        run: nix flake metadata --no-write-lock-file
      - name: nix flake outputs.
        run: nix flake show --no-write-lock-file

